return {
  -- {
  --   "navarasu/onedark.nvim",
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   config = function()
  --     require("onedark").setup({
  --       style = "darker",
  --     })
  --     -- Enable theme
  --     require("onedark").load()
  --   end,
  -- },
  -- {
  --   "rockyzhang24/arctic.nvim",
  --   dependencies = { "rktjmp/lush.nvim" },
  --   name = "arctic",
  --   branch = "main",
  --   priority = 1000,
  --   config = function()
  --     vim.cmd("colorscheme arctic")
  --   end,
  -- },
}
